# Change these first
owner: sixto1982 # Your GitHub organization or username, where this repository lives
repo: monitoreo # The name of this repository

sites:
  - name: iem-pro(front-Production)
    url: https://www.iem-pro.cl
    icon: https://www.iem-pro.cl/assets/icons/favico-150x150.ico
    
assignees:
  - sixto1982

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  logoUrl: https://iem-pro.cl/assets/images/Logo_Icarus2.jpeg
  cname: upptime.js.org
  name: Upptime
  baseUrl: /monitoreo
  introTitle: "Iem-pro"
  introMessage: Icarus Chile
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: iem-pro
      href: https://www.iem-pro.cl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
